### PR TITLE
Add The Ability to Register Preconnection Callbacks

### PR DESCRIPTION
**Pull request by DarkArc**
We needed the ability to perform certain operations before the websocket reconnects.

This adds the ability to register callbacks which must return promises, these promises must then be successfully fufilled before the websocket makes a reconnection attempt.

### CODE REVIEW

**Comment by DarkArc** [comment]
Sorry, reopened so that further work can be done on the master branch of the fork. Github currently doesn't allow you to change the branch you're pulling.

**Comment by b264** [comment]
Where is `preConnectionCallbacks` set from?

**Comment by DarkArc** [comment]
@b264 The thought is one can just modify the array ex

```javascript
ActionCableSocketWrangler.preConnectionCallbacks().push(myFunctionThatReturnsAPromise);
```

**Comment by b264** [comment]
Would you add it to the documentation and rebase on master?  It can be in version 1.4.0

**Comment by DarkArc** [comment]
Done and done. :)

**Comment by b264** [comment]
Just waiting on Travis

**Comment by b264** [comment]
build is failing

**Comment by DarkArc** [comment]
Odd seems to be failing from `Some of your tests did a full page reload!` now.

**Comment by b264** [comment]
https://github.com/angular-actioncable/angular-actioncable/issues/23 appears to be a framework bug.  I restarted the build and it passed

**Pull request merged**
